### ISSUE TITLE
Example docker-compose config doesn't work

### ISSUE THREAD

**Issue by resurge** [athensresearch/athens-backend#8]
Hi,
When I try running the example docker-compose.yml I'm not getting anything to work.
I'm very confused to how this is supposed to work.

## 1. Ports are incorrect
In #1 it is said that the container's external port is listening to internal port 13337 because the docker container listens to that by default.
But this does not seem to be the case.
I notice that when i `exec` into the running container and perform `curl -v localhost:13337` I get the response `curl: (7) Failed to connect to localhost port 13337: Connection refused`
However, when I perform `curl -v localhost:1337` I do get a response, but it has status code 404.
This suggests to me that:
  a. the internal port is misconfigured
  b. that something is going wrong internally because I'm not getting a proper http response.

For point b., am I maybe misunderstanding what athens-backend is for?
I was expecting to get athens' ui in a web browser. or is this solely a server to sync changes with desktop apps?

## 2. Unofficial image
Which brings me to point 2, why is the image [erulabs/athens-backend](https://hub.docker.com/r/erulabs/athens-backend) being used?  
I would expect athensresearch to have their own image of athens-backend on docker hub.
Not to disrespect @erulabs' work of course, it just seems out of place to use an unofficial image in an official repo's examples.

I see that erulabs' image on docker hub was last updated 10 days ago, but #1 was merged 4 days ago, maybe there's changes in the image that aren't published on Docker hub yet?

I hope I don't come across as too crass or entitled.
I've been looking forward for a long while to getting this to run web based :)
Thank you for building this.

**Comment by derek-j-pitman** [comment]
For your question 1: I noticed the incorrect port too and created [this pull request](https://github.com/athensresearch/athens-backend/pull/6) to update the documentation and the docker-compose.yml (tl;dr - replace `-p 13337:13337` with `-p 13337:1337`). Not sure why the app inside the container doesn't respect the `HTTP_PORT`, whether that's a Docker issue or an Athens issue.

Couldn't tell you whether trying to access the backend via web browser will give you an instance, the README suggests to me that you set that as your database target from the Athens client instead of using an on-disk DB. Maybe with the correct Docker config you can try it out and report back?

**Comment by resurge** [comment]
> the README suggests to me that you set that as your database target from the Athens client instead of using an on-disk DB

I went by the README of the [athens repo](https://github.com/athensresearch/athens)
> You can use Athens as a local desktop app that saves data to your filesystem or with a self-hosted server.

I interpreted it as:
> You can use Athens as (a local desktop app that saves data to your filesystem) or (with a self-hosted server).
But I guess this is meant:
> You can use Athens as a local desktop app that saves data (to your filesystem) or (with a self-hosted server).

I'll try it out if I find some time tomorrow.

**Comment by resurge** [comment]
I tried it out.
After changing the internal port to  the correct one (1337) and using the desktop app to connect to the backend everything worked as expected.

So @derek-j-pitman, [your PR](https://github.com/athensresearch/athens-backend/pull/6) will the port problem. 
And that the backend would present a web UI was a misunderstanding on my part.
The point of having an unofficial image in the repo still stands, but it would probably be cleaner in a separate issue.

I'll close this issue.
